---
date: "Friday, October 24, 2014"
output:
  html_document:
    keep_md: yes
    theme: united
---

I am working my way through the (excellent) text [Forecasting: principles and practice](http://otexts.org/fpp/), written by [R. Hyndman](http://robjhyndman.com/) and G. Athanasopoulos.   
The sample code and exercises provided in the text, combined with the **R [forecast](http://cran.r-project.org/web/packages/forecast/index.html) **package offers an infinite opportunity to test and examine time series data in simple but revealing ways.  In order to ease that exploration, this interactive tool implements some of the examples from Chapter 8.  Specific functions implemented here are:   
- [Stationarity and Differencing](https://www.otexts.org/fpp/8/1)   
- Autocorrelation function estimation   
- [Seasonal](https://www.otexts.org/fpp/8/9) and [Non-seasonal](https://www.otexts.org/fpp/8/5) ARIMA models

### ARIMA Models   
ARIMA is an acronym for AutoRegressive Integrated Moving Average model (“integration” in this context is the reverse of differencing).  The notation for non-seasonal models is ARIMA(p,d,q) where:   

p = order of the autoregressive part   
d = degree of first differencing involved   
q = order of the moving average part   

For seasonal models, the notation is ARIMA(p,d,q)(P,D,Q)m, where:   

P = order of the seasonal autoregressive part   
D = degree of seasonal first differencing involved   
Q = order of the seasonal moving average part   
m = number of periods per season   

###References:   
  
Hyndman, R.J. and Athanasopoulos, G. (2013) Forecasting: principles and practice. http://otexts.org/fpp/. Accessed on `r date()`    